export interface Country {
    code: string;
    name: string;
    dialCode: string;
    flag: string;
}

const flag = (code: string) =>
    code
        .toUpperCase()
        .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));

export const countries: Country[] = [
    { code: 'AF', name: 'Afghanistan', dialCode: '+93', flag: flag('AF') },
    { code: 'AL', name: 'Albania', dialCode: '+355', flag: flag('AL') },
    { code: 'DZ', name: 'Algeria', dialCode: '+213', flag: flag('DZ') },
    { code: 'AS', name: 'American Samoa', dialCode: '+1', flag: flag('AS') },
    { code: 'AD', name: 'Andorra', dialCode: '+376', flag: flag('AD') },
    { code: 'AO', name: 'Angola', dialCode: '+244', flag: flag('AO') },
    { code: 'AI', name: 'Anguilla', dialCode: '+1', flag: flag('AI') },
    { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1', flag: flag('AG') },
    { code: 'AR', name: 'Argentina', dialCode: '+54', flag: flag('AR') },
    { code: 'AM', name: 'Armenia', dialCode: '+374', flag: flag('AM') },
    { code: 'AW', name: 'Aruba', dialCode: '+297', flag: flag('AW') },
    { code: 'AU', name: 'Australia', dialCode: '+61', flag: flag('AU') },
    { code: 'AT', name: 'Austria', dialCode: '+43', flag: flag('AT') },
    { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', flag: flag('AZ') },
    { code: 'BS', name: 'Bahamas', dialCode: '+1', flag: flag('BS') },
    { code: 'BH', name: 'Bahrain', dialCode: '+973', flag: flag('BH') },
    { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: flag('BD') },
    { code: 'BB', name: 'Barbados', dialCode: '+1', flag: flag('BB') },
    { code: 'BY', name: 'Belarus', dialCode: '+375', flag: flag('BY') },
    { code: 'BE', name: 'Belgium', dialCode: '+32', flag: flag('BE') },
    { code: 'BZ', name: 'Belize', dialCode: '+501', flag: flag('BZ') },
    { code: 'BJ', name: 'Benin', dialCode: '+229', flag: flag('BJ') },
    { code: 'BM', name: 'Bermuda', dialCode: '+1', flag: flag('BM') },
    { code: 'BT', name: 'Bhutan', dialCode: '+975', flag: flag('BT') },
    { code: 'BO', name: 'Bolivia', dialCode: '+591', flag: flag('BO') },
    { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', flag: flag('BA') },
    { code: 'BW', name: 'Botswana', dialCode: '+267', flag: flag('BW') },
    { code: 'BR', name: 'Brazil', dialCode: '+55', flag: flag('BR') },
    { code: 'BN', name: 'Brunei', dialCode: '+673', flag: flag('BN') },
    { code: 'BG', name: 'Bulgaria', dialCode: '+359', flag: flag('BG') },
    { code: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: flag('BF') },
    { code: 'BI', name: 'Burundi', dialCode: '+257', flag: flag('BI') },
    { code: 'KH', name: 'Cambodia', dialCode: '+855', flag: flag('KH') },
    { code: 'CM', name: 'Cameroon', dialCode: '+237', flag: flag('CM') },
    { code: 'CA', name: 'Canada', dialCode: '+1', flag: flag('CA') },
    { code: 'CV', name: 'Cape Verde', dialCode: '+238', flag: flag('CV') },
    { code: 'KY', name: 'Cayman Islands', dialCode: '+1', flag: flag('KY') },
    { code: 'CF', name: 'Central African Republic', dialCode: '+236', flag: flag('CF') },
    { code: 'TD', name: 'Chad', dialCode: '+235', flag: flag('TD') },
    { code: 'CL', name: 'Chile', dialCode: '+56', flag: flag('CL') },
    { code: 'CN', name: 'China', dialCode: '+86', flag: flag('CN') },
    { code: 'CO', name: 'Colombia', dialCode: '+57', flag: flag('CO') },
    { code: 'KM', name: 'Comoros', dialCode: '+269', flag: flag('KM') },
    { code: 'CG', name: 'Congo', dialCode: '+242', flag: flag('CG') },
    { code: 'CD', name: 'Congo (DRC)', dialCode: '+243', flag: flag('CD') },
    { code: 'CK', name: 'Cook Islands', dialCode: '+682', flag: flag('CK') },
    { code: 'CR', name: 'Costa Rica', dialCode: '+506', flag: flag('CR') },
    { code: 'CI', name: "Côte d'Ivoire", dialCode: '+225', flag: flag('CI') },
    { code: 'HR', name: 'Croatia', dialCode: '+385', flag: flag('HR') },
    { code: 'CU', name: 'Cuba', dialCode: '+53', flag: flag('CU') },
    { code: 'CY', name: 'Cyprus', dialCode: '+357', flag: flag('CY') },
    { code: 'CZ', name: 'Czech Republic', dialCode: '+420', flag: flag('CZ') },
    { code: 'DK', name: 'Denmark', dialCode: '+45', flag: flag('DK') },
    { code: 'DJ', name: 'Djibouti', dialCode: '+253', flag: flag('DJ') },
    { code: 'DM', name: 'Dominica', dialCode: '+1', flag: flag('DM') },
    { code: 'DO', name: 'Dominican Republic', dialCode: '+1', flag: flag('DO') },
    { code: 'EC', name: 'Ecuador', dialCode: '+593', flag: flag('EC') },
    { code: 'EG', name: 'Egypt', dialCode: '+20', flag: flag('EG') },
    { code: 'SV', name: 'El Salvador', dialCode: '+503', flag: flag('SV') },
    { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', flag: flag('GQ') },
    { code: 'ER', name: 'Eritrea', dialCode: '+291', flag: flag('ER') },
    { code: 'EE', name: 'Estonia', dialCode: '+372', flag: flag('EE') },
    { code: 'SZ', name: 'Eswatini', dialCode: '+268', flag: flag('SZ') },
    { code: 'ET', name: 'Ethiopia', dialCode: '+251', flag: flag('ET') },
    { code: 'FJ', name: 'Fiji', dialCode: '+679', flag: flag('FJ') },
    { code: 'FI', name: 'Finland', dialCode: '+358', flag: flag('FI') },
    { code: 'FR', name: 'France', dialCode: '+33', flag: flag('FR') },
    { code: 'GF', name: 'French Guiana', dialCode: '+594', flag: flag('GF') },
    { code: 'PF', name: 'French Polynesia', dialCode: '+689', flag: flag('PF') },
    { code: 'GA', name: 'Gabon', dialCode: '+241', flag: flag('GA') },
    { code: 'GM', name: 'Gambia', dialCode: '+220', flag: flag('GM') },
    { code: 'GE', name: 'Georgia', dialCode: '+995', flag: flag('GE') },
    { code: 'DE', name: 'Germany', dialCode: '+49', flag: flag('DE') },
    { code: 'GH', name: 'Ghana', dialCode: '+233', flag: flag('GH') },
    { code: 'GI', name: 'Gibraltar', dialCode: '+350', flag: flag('GI') },
    { code: 'GR', name: 'Greece', dialCode: '+30', flag: flag('GR') },
    { code: 'GL', name: 'Greenland', dialCode: '+299', flag: flag('GL') },
    { code: 'GD', name: 'Grenada', dialCode: '+1', flag: flag('GD') },
    { code: 'GP', name: 'Guadeloupe', dialCode: '+590', flag: flag('GP') },
    { code: 'GU', name: 'Guam', dialCode: '+1', flag: flag('GU') },
    { code: 'GT', name: 'Guatemala', dialCode: '+502', flag: flag('GT') },
    { code: 'GN', name: 'Guinea', dialCode: '+224', flag: flag('GN') },
    { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', flag: flag('GW') },
    { code: 'GY', name: 'Guyana', dialCode: '+592', flag: flag('GY') },
    { code: 'HT', name: 'Haiti', dialCode: '+509', flag: flag('HT') },
    { code: 'HN', name: 'Honduras', dialCode: '+504', flag: flag('HN') },
    { code: 'HK', name: 'Hong Kong', dialCode: '+852', flag: flag('HK') },
    { code: 'HU', name: 'Hungary', dialCode: '+36', flag: flag('HU') },
    { code: 'IS', name: 'Iceland', dialCode: '+354', flag: flag('IS') },
    { code: 'IN', name: 'India', dialCode: '+91', flag: flag('IN') },
    { code: 'ID', name: 'Indonesia', dialCode: '+62', flag: flag('ID') },
    { code: 'IR', name: 'Iran', dialCode: '+98', flag: flag('IR') },
    { code: 'IQ', name: 'Iraq', dialCode: '+964', flag: flag('IQ') },
    { code: 'IE', name: 'Ireland', dialCode: '+353', flag: flag('IE') },
    { code: 'IL', name: 'Israel', dialCode: '+972', flag: flag('IL') },
    { code: 'IT', name: 'Italy', dialCode: '+39', flag: flag('IT') },
    { code: 'JM', name: 'Jamaica', dialCode: '+1', flag: flag('JM') },
    { code: 'JP', name: 'Japan', dialCode: '+81', flag: flag('JP') },
    { code: 'JO', name: 'Jordan', dialCode: '+962', flag: flag('JO') },
    { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', flag: flag('KZ') },
    { code: 'KE', name: 'Kenya', dialCode: '+254', flag: flag('KE') },
    { code: 'KI', name: 'Kiribati', dialCode: '+686', flag: flag('KI') },
    { code: 'KW', name: 'Kuwait', dialCode: '+965', flag: flag('KW') },
    { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', flag: flag('KG') },
    { code: 'LA', name: 'Laos', dialCode: '+856', flag: flag('LA') },
    { code: 'LV', name: 'Latvia', dialCode: '+371', flag: flag('LV') },
    { code: 'LB', name: 'Lebanon', dialCode: '+961', flag: flag('LB') },
    { code: 'LS', name: 'Lesotho', dialCode: '+266', flag: flag('LS') },
    { code: 'LR', name: 'Liberia', dialCode: '+231', flag: flag('LR') },
    { code: 'LY', name: 'Libya', dialCode: '+218', flag: flag('LY') },
    { code: 'LI', name: 'Liechtenstein', dialCode: '+423', flag: flag('LI') },
    { code: 'LT', name: 'Lithuania', dialCode: '+370', flag: flag('LT') },
    { code: 'LU', name: 'Luxembourg', dialCode: '+352', flag: flag('LU') },
    { code: 'MO', name: 'Macau', dialCode: '+853', flag: flag('MO') },
    { code: 'MG', name: 'Madagascar', dialCode: '+261', flag: flag('MG') },
    { code: 'MW', name: 'Malawi', dialCode: '+265', flag: flag('MW') },
    { code: 'MY', name: 'Malaysia', dialCode: '+60', flag: flag('MY') },
    { code: 'MV', name: 'Maldives', dialCode: '+960', flag: flag('MV') },
    { code: 'ML', name: 'Mali', dialCode: '+223', flag: flag('ML') },
    { code: 'MT', name: 'Malta', dialCode: '+356', flag: flag('MT') },
    { code: 'MH', name: 'Marshall Islands', dialCode: '+692', flag: flag('MH') },
    { code: 'MQ', name: 'Martinique', dialCode: '+596', flag: flag('MQ') },
    { code: 'MR', name: 'Mauritania', dialCode: '+222', flag: flag('MR') },
    { code: 'MU', name: 'Mauritius', dialCode: '+230', flag: flag('MU') },
    { code: 'MX', name: 'Mexico', dialCode: '+52', flag: flag('MX') },
    { code: 'FM', name: 'Micronesia', dialCode: '+691', flag: flag('FM') },
    { code: 'MD', name: 'Moldova', dialCode: '+373', flag: flag('MD') },
    { code: 'MC', name: 'Monaco', dialCode: '+377', flag: flag('MC') },
    { code: 'MN', name: 'Mongolia', dialCode: '+976', flag: flag('MN') },
    { code: 'ME', name: 'Montenegro', dialCode: '+382', flag: flag('ME') },
    { code: 'MS', name: 'Montserrat', dialCode: '+1', flag: flag('MS') },
    { code: 'MA', name: 'Morocco', dialCode: '+212', flag: flag('MA') },
    { code: 'MZ', name: 'Mozambique', dialCode: '+258', flag: flag('MZ') },
    { code: 'MM', name: 'Myanmar', dialCode: '+95', flag: flag('MM') },
    { code: 'NA', name: 'Namibia', dialCode: '+264', flag: flag('NA') },
    { code: 'NR', name: 'Nauru', dialCode: '+674', flag: flag('NR') },
    { code: 'NP', name: 'Nepal', dialCode: '+977', flag: flag('NP') },
    { code: 'NL', name: 'Netherlands', dialCode: '+31', flag: flag('NL') },
    { code: 'NC', name: 'New Caledonia', dialCode: '+687', flag: flag('NC') },
    { code: 'NZ', name: 'New Zealand', dialCode: '+64', flag: flag('NZ') },
    { code: 'NI', name: 'Nicaragua', dialCode: '+505', flag: flag('NI') },
    { code: 'NE', name: 'Niger', dialCode: '+227', flag: flag('NE') },
    { code: 'NG', name: 'Nigeria', dialCode: '+234', flag: flag('NG') },
    { code: 'NU', name: 'Niue', dialCode: '+683', flag: flag('NU') },
    { code: 'NF', name: 'Norfolk Island', dialCode: '+672', flag: flag('NF') },
    { code: 'KP', name: 'North Korea', dialCode: '+850', flag: flag('KP') },
    { code: 'MK', name: 'North Macedonia', dialCode: '+389', flag: flag('MK') },
    { code: 'NO', name: 'Norway', dialCode: '+47', flag: flag('NO') },
    { code: 'OM', name: 'Oman', dialCode: '+968', flag: flag('OM') },
    { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: flag('PK') },
    { code: 'PW', name: 'Palau', dialCode: '+680', flag: flag('PW') },
    { code: 'PS', name: 'Palestine', dialCode: '+970', flag: flag('PS') },
    { code: 'PA', name: 'Panama', dialCode: '+507', flag: flag('PA') },
    { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', flag: flag('PG') },
    { code: 'PY', name: 'Paraguay', dialCode: '+595', flag: flag('PY') },
    { code: 'PE', name: 'Peru', dialCode: '+51', flag: flag('PE') },
    { code: 'PH', name: 'Philippines', dialCode: '+63', flag: flag('PH') },
    { code: 'PL', name: 'Poland', dialCode: '+48', flag: flag('PL') },
    { code: 'PT', name: 'Portugal', dialCode: '+351', flag: flag('PT') },
    { code: 'PR', name: 'Puerto Rico', dialCode: '+1', flag: flag('PR') },
    { code: 'QA', name: 'Qatar', dialCode: '+974', flag: flag('QA') },
    { code: 'RE', name: 'Réunion', dialCode: '+262', flag: flag('RE') },
    { code: 'RO', name: 'Romania', dialCode: '+40', flag: flag('RO') },
    { code: 'RU', name: 'Russia', dialCode: '+7', flag: flag('RU') },
    { code: 'RW', name: 'Rwanda', dialCode: '+250', flag: flag('RW') },
    { code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1', flag: flag('KN') },
    { code: 'LC', name: 'Saint Lucia', dialCode: '+1', flag: flag('LC') },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1', flag: flag('VC') },
    { code: 'WS', name: 'Samoa', dialCode: '+685', flag: flag('WS') },
    { code: 'SM', name: 'San Marino', dialCode: '+378', flag: flag('SM') },
    { code: 'ST', name: 'São Tomé and Príncipe', dialCode: '+239', flag: flag('ST') },
    { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: flag('SA') },
    { code: 'SN', name: 'Senegal', dialCode: '+221', flag: flag('SN') },
    { code: 'RS', name: 'Serbia', dialCode: '+381', flag: flag('RS') },
    { code: 'SC', name: 'Seychelles', dialCode: '+248', flag: flag('SC') },
    { code: 'SL', name: 'Sierra Leone', dialCode: '+232', flag: flag('SL') },
    { code: 'SG', name: 'Singapore', dialCode: '+65', flag: flag('SG') },
    { code: 'SK', name: 'Slovakia', dialCode: '+421', flag: flag('SK') },
    { code: 'SI', name: 'Slovenia', dialCode: '+386', flag: flag('SI') },
    { code: 'SB', name: 'Solomon Islands', dialCode: '+677', flag: flag('SB') },
    { code: 'SO', name: 'Somalia', dialCode: '+252', flag: flag('SO') },
    { code: 'ZA', name: 'South Africa', dialCode: '+27', flag: flag('ZA') },
    { code: 'KR', name: 'South Korea', dialCode: '+82', flag: flag('KR') },
    { code: 'SS', name: 'South Sudan', dialCode: '+211', flag: flag('SS') },
    { code: 'ES', name: 'Spain', dialCode: '+34', flag: flag('ES') },
    { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: flag('LK') },
    { code: 'SD', name: 'Sudan', dialCode: '+249', flag: flag('SD') },
    { code: 'SR', name: 'Suriname', dialCode: '+597', flag: flag('SR') },
    { code: 'SE', name: 'Sweden', dialCode: '+46', flag: flag('SE') },
    { code: 'CH', name: 'Switzerland', dialCode: '+41', flag: flag('CH') },
    { code: 'SY', name: 'Syria', dialCode: '+963', flag: flag('SY') },
    { code: 'TW', name: 'Taiwan', dialCode: '+886', flag: flag('TW') },
    { code: 'TJ', name: 'Tajikistan', dialCode: '+992', flag: flag('TJ') },
    { code: 'TZ', name: 'Tanzania', dialCode: '+255', flag: flag('TZ') },
    { code: 'TH', name: 'Thailand', dialCode: '+66', flag: flag('TH') },
    { code: 'TL', name: 'Timor-Leste', dialCode: '+670', flag: flag('TL') },
    { code: 'TG', name: 'Togo', dialCode: '+228', flag: flag('TG') },
    { code: 'TO', name: 'Tonga', dialCode: '+676', flag: flag('TO') },
    { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1', flag: flag('TT') },
    { code: 'TN', name: 'Tunisia', dialCode: '+216', flag: flag('TN') },
    { code: 'TR', name: 'Turkey', dialCode: '+90', flag: flag('TR') },
    { code: 'TM', name: 'Turkmenistan', dialCode: '+993', flag: flag('TM') },
    { code: 'TC', name: 'Turks and Caicos Islands', dialCode: '+1', flag: flag('TC') },
    { code: 'TV', name: 'Tuvalu', dialCode: '+688', flag: flag('TV') },
    { code: 'UG', name: 'Uganda', dialCode: '+256', flag: flag('UG') },
    { code: 'UA', name: 'Ukraine', dialCode: '+380', flag: flag('UA') },
    { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', flag: flag('AE') },
    { code: 'GB', name: 'United Kingdom', dialCode: '+44', flag: flag('GB') },
    { code: 'US', name: 'United States', dialCode: '+1', flag: flag('US') },
    { code: 'UY', name: 'Uruguay', dialCode: '+598', flag: flag('UY') },
    { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', flag: flag('UZ') },
    { code: 'VU', name: 'Vanuatu', dialCode: '+678', flag: flag('VU') },
    { code: 'VA', name: 'Vatican City', dialCode: '+39', flag: flag('VA') },
    { code: 'VE', name: 'Venezuela', dialCode: '+58', flag: flag('VE') },
    { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: flag('VN') },
    { code: 'VI', name: 'Virgin Islands (US)', dialCode: '+1', flag: flag('VI') },
    { code: 'YE', name: 'Yemen', dialCode: '+967', flag: flag('YE') },
    { code: 'ZM', name: 'Zambia', dialCode: '+260', flag: flag('ZM') },
    { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: flag('ZW') },
];

export const defaultCountry = countries.find((c) => c.code === 'CA') ?? countries[0];
